### ISSUE TITLE
Preact

### ISSUE THREAD

**Issue by Ayc0** [rstacruz/remount#3]
Do you plan to support preact, which is better suited for web components because of its weight?

**Comment by httpiago** [comment]
I liked the idea, would be great especially for sites that do not use this package very much.

**Comment by rstacruz** [comment]
It should work with preact using preact-compat!

**Comment by rstacruz** [comment]
It should also be possible to write Remount integration with Preact or any other library using custom strategies:

https://github.com/rstacruz/remount/blob/master/docs/api.md#custom-adapters

Getting support built into 
`remount` isn't planned at the moment, but if enough people are interested, I can put together a remount-preact package (and remount-elm, remount-deku, etc) :)

**Comment by dy** [comment]
Would be nice to have these preset adapters directly in `remount` as `remount/adapters/deku` etc., compared to installing a bunch of separate packages.

**Comment by Ayc0** [comment]
With Preact X, it will be easy to create the bindings.
But I'm right with you @dy, maybe having a set of already defined adapters could be a good idea!

**Comment by Ayc0** [comment]
Also, I've tried to create my own adapter, and I've got this even if I'm not using React

```
🚨  ~/preact-x-test/node_modules/remount/dist/remount.esm.mjs:1:30: Cannot resolve dependency 'react'
> 1 | import { createElement } from 'react';
    |                              ^
  2 | import ReactDOM from 'react-dom';
  3 | 
  4 | /* global HTMLElement */
```

**Comment by rstacruz** [comment]
Ooh, interesting - I think this is something we can (should?) address. I've been wanting to get Remount to work on non-React environments too.
