### ISSUE TITLE
Autoparse attribute values / propTypes

### ISSUE THREAD

**Issue by dy** [rstacruz/remount#6]
There is [auto-parse](https://github.com/greenpioneersolutions/auto-parse) package, that detects typed value from string attribute and parses that correspondingly.
Taking into account component's `propTypes` it would be handy to have automatic attributes parser to corresponding type.
Does that make sense @rstacruz?

**Comment by rstacruz** [comment]
Thanks for this! It was a deliberate design decision to only allow strings.

jQuery had this behavior with its `jQuery.fn.data` - it tries to auto-coerce types similar to the `auto-parse` package. This was considered a bad move by many:

- http://lookfirst.com/2011/12/dont-use-jquery-data-method-use-attr.html
- https://stackoverflow.com/questions/26126017/html5-data-attribute-type-casting-strings-and-numbers

In my opinion, this breaks the [Principle of Least Astonishment](https://en.m.wikipedia.org/wiki/Principle_of_least_astonishment) and would rather let this be handled in userland.

```js
define({
  'your-component': ({ name }) => (
    <YourComponent name={autoParse(name)} />
  )
}, attributes: ['name'])
```
