### ISSUE TITLE
ReactDOM.render is deprecated for React 18

### ISSUE THREAD

**Issue by AlexisMunozC** [rstacruz/remount#73]
Hi, I am using remount with React 18 and I am getting this warning because you are using render instead createRoot for React 18.
![image](https://user-images.githubusercontent.com/40778810/161449355-695f5764-3870-4b64-b515-c41dc1bb0bd4.png)

**Comment by rstacruz** [comment]
Thanks for the report! Looks like there's a few stuff that would need to be updated. In the mean time, it should continue to work (though it will trigger a warning).

**Comment by alec-c4** [comment]
hey! any updates with this issue?

**Comment by jdubs1994** [comment]
Bump ^^

**Comment by rstacruz** [comment]
Fixed in remount@1.0.0 :tada: Thanks for the report!
